---
title: "Plots_interaction"
author: "Rob van der Wielen"
date: "2023-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(gridExtra)
```

#--- Loading in Data ---#

```{r}
regressionData <- read.csv("C:/Users/Systeembeheer/OneDrive - Tilburg University/Documenten/Master/Marketing Analytics/Thesis/ThesisRob/ThesisRob/Datasets/Cleaned_data/RegressionData.csv")

```

#--- Creating interaction plot for genre variable ---#

```{r}
pdf("plots/interaction_mpaa.pdf") 

# Calculate mean and standard deviation of Holiday_distance
mean_distance <- mean(regressionData$Holiday_distance)
sd_distance <- sd(regressionData$Holiday_distance)

# Calculate the thresholds for the three levels
level_above_mean <- mean_distance + sd_distance
level_below_mean <- mean_distance - sd_distance

# Categorize Holiday_distance into three levels
regressionData$Holiday_level <- cut(regressionData$Holiday_distance, breaks = c(-Inf, level_below_mean, level_above_mean, Inf),
                                    labels = c("1 SD Below Mean", "Within 1 SD", "1 SD Above Mean"))

# Plot the moderation effect
plot <- ggplot(regressionData, aes(x = AVG_Nmpaa_comp, y = cumulative_rank, color = Holiday_level)) +
  geom_smooth(method = "lm", se = FALSE, size = 1.2, linetype = "dashed") +
  scale_color_manual(values = c("#6BAED6", "#FD8D3C", "#66CC99"),
                     labels = c("1 SD Below Mean", "Within 1 SD", "1 SD Above Mean")) +
  labs(x = "Average amount of competitor MPAA videos", y = "Cumulative rank in weeks",
       color = "Holiday distance") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_cartesian(ylim = c(1, 5))  # Adjust the lower and upper limits of the y-axis as desired

# Display the plot
plot
```




```{r}
pdf("plots/interaction_genre.pdf") 

# Calculate mean and standard deviation of Holiday_distance
mean_distance <- mean(regressionData$Holiday_distance)
sd_distance <- sd(regressionData$Holiday_distance)

# Calculate the thresholds for the three levels
level_above_mean <- mean_distance + sd_distance
level_below_mean <- mean_distance - sd_distance

# Categorize Holiday_distance into three levels
regressionData$Holiday_level <- cut(regressionData$Holiday_distance, breaks = c(-Inf, level_below_mean, level_above_mean, Inf),
                                    labels = c("1 SD Below Mean", "Within 1 SD", "1 SD Above Mean"))

# Plot the moderation effect
plot <- ggplot(regressionData, aes(x = AVG_Ngenre_comp, y = cumulative_rank, color = Holiday_level)) +
  geom_smooth(method = "lm", se = FALSE, size = 1.2, linetype = "dashed") +
  scale_color_manual(values = c("#6BAED6", "#FD8D3C", "#66CC99")) +
  labs(x = "Average amount of competitor genre videos", y = "Cumulative rank in weeks",
       color = "Holiday distance") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_cartesian(ylim = c(1, 5))  # Adjust the lower and upper limits of the y-axis as desired

# Display the plot
plot
```
