---
title: "Analysis"
author: "Rob van der Wielen"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#--- Install packages ---#

```{r}
install.packages("modelsummary")
```

#--- Libraries---#

```{r}
library(modelsummary)
library(flextable)
```


#--- Loading in Data ---#

```{r}
regressionData <- read.csv("RegressionData.csv")
```


#--- Model 1 (without interaction) ---#
```{r}
model1 <- lm(log(cumulative_rank) ~ 
               AVG_Nmpaa_comp + 
               AVG_Ngenre_comp + 
               rating + 
               exclusive + 
               Type + 
               sequel, 
             data = regressionData)
summary(model1) 

```


#--- Model 2 (with interaction) ---#
```{r}

model2 <- lm(log(cumulative_rank) ~ 
              AVG_Nmpaa_comp*Holiday_distance+ 
              AVG_Ngenre_comp*Holiday_distance+ 
               rating + 
               exclusive + 
               Type + 
               sequel, 
             data = regressionData)
summary(model2) 
``` 


#--- Model 3 only control variables ---#
```{r}

model3 <- lm(log(cumulative_rank) ~ 
               rating + 
               exclusive + 
               Type + 
               sequel, 
             data = regressionData)
summary(model3) 
```

#--- Model 4 (with interaction mpaa rating) ---#
```{r}
model4 <- lm(log(cumulative_rank) ~ 
               AVG_Nmpaa_comp*Holiday_distance+ 
               rating + 
               exclusive + 
               Type + 
               sequel, 
             data = regressionData)
summary(model4) 
```

#--- Model 5 (with interaction genre) ---#

```{r}
model5 <- lm(log(cumulative_rank) ~ 
               AVG_Ngenre_comp*Holiday_distance+ 
               rating + 
               exclusive + 
               Type + 
               sequel, 
             data = regressionData)
summary(model5) 
```



#--- F change ---#
```{r}
anova(model2, model4, test = "F")
```


#--- Creating model ---#
```{r}
#insert models 
models <- list("Model 1"=model1, "Model 2"=model2)


gm <- tibble::tribble(
  ~raw, ~clean, ~fmt,
  "nobs", "N", 0,
  "r.squared", "R<sup>2</sup>", 3,
  "adj.r.squared", "Adjusted R<sup>2</sup>", 3,
  "F", "F statistic", 3)


statistical_model <- modelsummary(models,
                                  coef_rename = c('(Intercept)' = 'Intercept', 
                                                  'AVG_Ngenre_comp' = 'Amount competitor genre videos',
                                                  'AVG_Nmpaa_comp' = 'Amount competitor MPAA videos',
                                                  'Holiday_distance' = 'Holiday distance',
                                                  'rating' = 'Rating',
                                                  'exclusive' = 'Netflix Exclusive',
                                                  'Type' = 'Movie',
                                                  'sequel' = 'Sequel',
                                                  'AVG_Ngenre_comp:Holiday_distance' = 'Amount competitor genre videos * Holiday Distance',
                                                   'AVG_Nmpaa_comp:Holiday_distance' = 'Amount competitor MPAA videos * Holiday Distance'),estimate = "{estimate}{stars}",
                                  fmt = 3,
                                  stars = c(' ∙' = 0.1, '*' = 0.05, '**' = 0.01, '***' = 0.01),
                                  gof_map = gm,
                                  output = "table.docx",
                                  notes = 'Note: The dependent variable in all the models is the cumulative weeks spend in the Netflix top ten. The dependent variable is log-transformed.')

statistical_model

```



```{r}
#insert models 
models <- list("Model 3"=model3)


gm <- tibble::tribble(
  ~raw, ~clean, ~fmt,
  "nobs", "N", 0,
  "r.squared", "R<sup>2</sup>", 3,
  "adj.r.squared", "Adjusted R<sup>2</sup>", 3,
  "F", "F statistic", 3)


statistical_model_3 <- modelsummary(models,
                                  coef_rename = c('(Intercept)' = 'Intercept', 
                                                  'AVG_Ngenre_comp' = 'Amount competitor genre videos',
                                                  'AVG_Nmpaa_comp' = 'Amount competitor MPAA videos',
                                                  'Holiday_distance' = 'Holiday distance',
                                                  'rating' = 'Rating',
                                                  'exclusive' = 'Netflix Exclusive',
                                                  'Type' = 'Movie',
                                                  'sequel' = 'Sequel',
                                                  'Holiday_distance:AVG_Ngenre_comp' = 'Amount competitor genre videos * Holiday Distance',
                                                   'AVG_Nmpaa_comp:Holiday_distance' = 'Amount competitor MPAA videos * Holiday Distance'),estimate = "{estimate}{stars}",
                                  fmt = 3,
                                  stars = c(' ∙' = 0.1, '*' = 0.05, '**' = 0.01, '***' = 0.01),
                                  gof_map = gm,
                                  output = "table3.docx",
                                  notes = 'Note: The dependent variable in all the models is the cumulative weeks spend in the Netflix top ten. The dependent variable is log-transformed.')

statistical_model_3

```



#--- Creating model ---#
```{r}
#insert models 
models <- list("Model 1"=model1, "Model 4"=model4, "Model 5"=model5)


gm <- tibble::tribble(
  ~raw, ~clean, ~fmt,
  "nobs", "N", 0,
  "r.squared", "R<sup>2</sup>", 3,
  "adj.r.squared", "Adjusted R<sup>2</sup>", 3,
  "F", "F statistic", 3)


statistical_model <- modelsummary(models,
                                  coef_rename = c('(Intercept)' = 'Intercept', 
                                                  'AVG_Ngenre_comp' = 'Amount competitor genre videos',
                                                  'AVG_Nmpaa_comp' = 'Amount competitor MPAA videos',
                                                  'Holiday_distance' = 'Holiday distance',
                                                  'rating' = 'Rating',
                                                  'exclusive' = 'Netflix Exclusive',
                                                  'Type' = 'Movie',
                                                  'sequel' = 'Sequel',
                                                  'AVG_Ngenre_comp:Holiday_distance' = 'Amount competitor genre videos * Holiday Distance',
                                                   'AVG_Nmpaa_comp:Holiday_distance' = 'Amount competitor MPAA videos * Holiday Distance'),estimate = "{estimate}{stars}",
                                  fmt = 3,
                                  stars = c(' ∙' = 0.1, '*' = 0.05, '**' = 0.01, '***' = 0.01),
                                  gof_map = gm,
                                  output = "table.docx",
                                  notes = 'Note: The dependent variable in all the models is the cumulative weeks spend in the Netflix top ten. The dependent variable is log-transformed.')

statistical_model

```

